---
#PT Grey Camera Config File
#NOTE:  ALL UNITS AND RANGES GIVEN ASSUME THAT THE CAMERA PROPERTIES
#       ARE BEING CONFIGURED IN "ABSOLUTE MODE" WHICH MEANS absControl FOR EACH
#       PROPERTY IS "TRUE"
#
#NOTE:  RANGE IS GIVEN AS SEEN IN FLYCAP2 SOFTWARE FOR CAMERA IN MODE_1 (2x2 binning; 640x480)
#       SEE "framerate"
#
#
#FROM DOCUMENTATION:
#setProperty(property = None, **kwargs) → None
#  Take strobe properties and update the camera’s strobe.
#  There are two ways to call this function: The first is with a Property object containing the updated properties 
#
#      The second is by specifying each property to update in the arguments. The arguments that can be specified are:
#
#        type (int)
#        present (bool)
#        absControl (bool)
#        onePush (bool)
#        onOff (bool)
#        autoManualMode (bool)
#        valueA (int)
#        valueB (int)
#        absValue (float)
#        Note that type MUST be specified if this method of calling is used.
#        Information about these properties can be found in the Property documentation.
#        Ex. camera.setProperty(type = PyCapture2.PROPERTY_TYPE.ZOOM, absValue = 2.0) Sets
#        zoom to 2.
#
#     Parameters
#     • property (PyCapture2.Property) – The property object to get all properties
#       from.
#     • kwargs ({...}) – The second method of calling: specify the properties to change as
#       keywords.
#
#class PyCapture2.Property
#    Data from a specific camera property.
#    Used to get and set property information.
#
#    type
#        PyCapture2.PROPERTY_TYPE – The type of property that is described with the following values.
#    present
#        bool – The flag controlling if the property is present on the camera.
#    absControl
#        bool – The flag controlling absolute mode (real world units) or non-absolute mode (camera internal units)
#    onePush
#        bool – The flag controlling one push.
#    onOff
#        bool – Flag controlling activation of property. [True = ON ; False = OFF]
#    autoManualMode
#       bool – Flag controlling auto/manual. [True = AUTO ; False = MANUAL]
#    ValueA
#       int – Value A
#    ValueB
#       int – Value B
#    absValue
#       float – Floating point value.
#
brightness:
  #unit: Percentage Point (%)
  #range: 1.367 : 7.422
  #Auto: un-available
  #ON/OFF: un-available
  #One Push: un-available
  type: PyCapture2.PROPERTY_TYPE.BRIGHTNESS
  present: True
  absControl: True
  onePush: 'None'
  onOff: 'True'
  autoManualMode: 'None'
  ValueA: 'None'
  ValueB: 'None'
  absValue: '1.367'
#
shutter:
  #unit: time in milliseconds (ms)
  #range: 0.52 : 17.527
  #Auto: available
  #ON/OFF: un-available
  #One Push: available
  type: PyCapture2.PROPERTY_TYPE.SHUTTER
  present: True
  absControl: True
  onePush: 'False'
  onOff: 'True'
  autoManualMode: 'True'
  ValueA: 'None'
  ValueB: 'None'
  absValue: '0.0'
#
gain:
  #units: Decibels (dB)
  #range: 0 : 23.991
  #Auto: available
  #ON/OFF: un-available
  #One Push: available
  type: PyCapture2.PROPERTY_TYPE.GAIN
  present: True
  absControl: True
  onePush: 'False'
  onOff: 'True'
  autoManualMode: 'True'
  ValueA: 'None'
  ValueB: 'None'
  absValue: '0.0'
#
#NOTE: Even though sharpness appears as a parameter on FlyCap2 for this camera, I get an error
#saying that it is not present when I try to set it.
#sharpness:
  #units: unclear
  #range: 0 : 4095
  #Auto: available
  #ON/OFF: un-available
  #One Push: un-available
#  type: PyCapture2.PROPERTY_TYPE.SHARPNESS
#  present: True
#  absControl: True
#  onePush: 'None'
#  onOff: 'True'
#  autoManualMode: 'True'
#  ValueA: 'None'
#  ValueB: 'None'
#  absValue: '0.0'
#
auto_exposure:
  #NOTE: I'm assuming this is what FlyCap2 refers to as "Exposure"
  #units: Exposure Value (EV)
  #range: -7.585 : 2.414
  #Auto: available
  #ON/OFF: available
  #One Push: available
  type: PyCapture2.PROPERTY_TYPE.AUTO_EXPOSURE
  present: True
  absControl: True
  onePush: 'False'
  onOff: 'True'
  autoManualMode: 'True'
  ValueA: 'None'
  ValueB: 'None'
  absValue: '0.0'
#
gamma:
  #units: unclear
  #range: .5 ; 3.999
  #Auto: un-available
  #ON/OFF: available
  #One Push: un-available
  type: PyCapture2.PROPERTY_TYPE.GAMMA
  present: True
  absControl: True
  onePush: 'None'
  onOff: 'False'
  autoManualMode: 'None'
  ValueA: 'None'
  ValueB: 'None'
  absValue: '0.0'
#
framerate:
  #units: Frames per Second (fps)
  #range: 1 : 55 (MODE_0 = 1 : 35; MODE_5 = 1 : 95)
  #Auto: available
  #ON/OFF: available
  #One Push: un-available
  type: PyCapture2.PROPERTY_TYPE.FRAME_RATE
  present: True
  absControl: True
  onePush: 'None'
  onOff: 'True'
  autoManualMode: 'False'
  ValueA: 'None'
  ValueB: 'None'
  absValue: '55.0'
...